apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftex

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: ftex-platform
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ftex/backend
    newTag: latest
  - name: ftex/frontend
    newTag: latest

